name: Release Package and Docs

on:
  push:
    branches:
      - main # 监听 main 分支的 push 事件

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Library
        run: npm run build # 确保 package.json 中有 build 脚本

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 需要先在 GitHub 配置 NPM_TOKEN

  deploy-docs:
    runs-on: ubuntu-latest
    needs: publish-package # 确保先发布包再部署文档
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Docs
        run: npm run docs:build # dumi 文档构建命令

      - - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 关键修复点：
          github_token: ${{ secrets.ACCESS_KEY }} # 推荐使用部署密钥
          # 或者改用 personal token：
          # github_token: ${{ secrets.GH_PAGES_TOKEN }}
          
          publish_dir: ./docs-dist
          keep_files: false # 建议关闭保留旧文件
          force_orphan: true # 强制清理历史记录
